{
    'name': 'ONMI RECITOTAL CUSTOMS',
    'version': '18.0.0.1',
    'summary': 'Customizations for Recitotal',
    'description': 'Customizations for Recitotal',
    'category':  'ONMI developments',
    'author': 'ONMI Engineering',
    'license': 'LGPL-3',
    'depends': ['l10n_es_vat_book',
                'base',
                'account',
                'account_edi',
                'contacts',
                'stock',
                'onmi_turbo_identification_document',
                'onmi_turbo_invoice_export_note',],
    'data': [
        'views/account_move_view.xml',
        'views/account_move_views.xml',
        'views/stock_picking_views.xml',
        'views/res_partner_views.xml',
        'report/report_invoice_document_template.xml',
        'report/report_export_invoice_document_template.xml',
        ],
    'installable': True,
    'application': True,
    'auto_install': False
}
